export const resources = [
  {
    id: "anthropic-claude-marketplace",
    title: "Claude Marketplace",
    source_url: "https://claude.ai/marketplace",
    platform: "Claude",
    source_category: "official marketplace",
    type: ["marketplace", "agent", "integration"],
    use_case: ["automation", "research", "operations", "knowledge management"],
    format: ["directory", "plugin", "connector"],
    adoption_mode: "combined",
    interaction_mode: ["chat", "tool-use", "workflow"],
    architecture: ["agent", "connectors", "skills"],
    maturity: "production",
    audience: ["teams", "operators", "developers"],
    tags: ["plugins", "connectors", "agents", "skills"],
    summary: "Official directory for discovering Claude-compatible products, agents, plugins, and connectors.",
    reusable_blocks: ["capability discovery", "connector selection", "agent composition"],
    license: "varies; verify per entry",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 89,
    notes: "Use as a discovery source; independently verify permissions, pricing, and maintenance."
  },
  {
    id: "openai-developer-showcase",
    title: "OpenAI Developer Showcase",
    source_url: "https://developers.openai.com/showcase",
    platform: "OpenAI",
    source_category: "official showcase",
    type: ["showcase", "demo", "use-case"],
    use_case: ["coding", "research", "automation", "creative"],
    format: ["gallery", "case study", "demo"],
    adoption_mode: "hybrid",
    interaction_mode: ["chat", "agent", "multimodal"],
    architecture: ["agent", "tool-use", "multimodal"],
    maturity: "mixed",
    audience: ["developers", "builders", "teams"],
    tags: ["apps", "agents", "demos", "solutions"],
    summary: "Collection of example applications and agentic solutions built with OpenAI technologies.",
    reusable_blocks: ["solution framing", "tool orchestration", "evaluation ideas"],
    license: "varies; verify per entry",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 88,
    notes: "Prioritize entries with runnable repos, explicit architecture, and reproducible steps."
  },
  {
    id: "openai-codex-learning",
    title: "Codex Learning and Workflow Resources",
    source_url: "https://developers.openai.com/learn/codex",
    platform: "Codex",
    source_category: "official documentation",
    type: ["docs", "workflow", "playbook"],
    use_case: ["coding", "devops", "automation"],
    format: ["guide", "docs", "workflow"],
    adoption_mode: "partial",
    interaction_mode: ["ide", "terminal", "agent"],
    architecture: ["repo-aware", "tool-use", "verification-loop"],
    maturity: "production",
    audience: ["developers", "engineering teams"],
    tags: ["coding", "repository", "testing", "patches"],
    summary: "Official learning material for applying Codex to software engineering workflows.",
    reusable_blocks: ["repository inspection", "change planning", "test-and-fix loop"],
    license: "see source",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 94,
    notes: "Strong candidate for extracting repeatable coding-agent protocols."
  },
  {
    id: "replit-community",
    title: "Replit Community Projects",
    source_url: "https://replit.com/community",
    platform: "Replit",
    source_category: "official community showcase",
    type: ["showcase", "app", "template"],
    use_case: ["coding", "prototyping", "education", "automation"],
    format: ["gallery", "app", "demo"],
    adoption_mode: "full",
    interaction_mode: ["browser", "ide", "agent"],
    architecture: ["full-stack", "runtime", "live-preview"],
    maturity: "mixed",
    audience: ["builders", "students", "startups"],
    tags: ["prototype", "full-stack", "live app", "templates"],
    summary: "Community-built applications and experiments useful for identifying practical build patterns.",
    reusable_blocks: ["app scaffold", "deployment loop", "feature iteration"],
    license: "varies; verify per project",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 82,
    notes: "Treat community projects as inspiration until dependencies, license, and maintenance are checked."
  },
  {
    id: "vercel-v0-components",
    title: "v0 Component Gallery",
    source_url: "https://v0.dev/components",
    platform: "Vercel v0",
    source_category: "official gallery",
    type: ["gallery", "template", "showcase"],
    use_case: ["design", "frontend", "product prototyping"],
    format: ["component", "gallery", "demo"],
    adoption_mode: "partial",
    interaction_mode: ["chat", "ui-generation"],
    architecture: ["frontend", "component", "design-to-code"],
    maturity: "production",
    audience: ["designers", "frontend engineers", "product teams"],
    tags: ["ui", "components", "design-to-code", "frontend"],
    summary: "Reusable interface examples for rapidly exploring and adapting frontend patterns.",
    reusable_blocks: ["component extraction", "visual iteration", "responsive layout"],
    license: "verify per generated artifact",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 86,
    notes: "Validate accessibility, responsiveness, security, and dependency quality before adoption."
  },
  {
    id: "google-ai-studio-templates",
    title: "Google AI Studio Templates",
    source_url: "https://aistudio.google.com/app/templates",
    platform: "Google Gemini",
    source_category: "official template gallery",
    type: ["gallery", "template", "use-case"],
    use_case: ["multimodal", "research", "content", "analysis"],
    format: ["template", "demo", "workflow"],
    adoption_mode: "hybrid",
    interaction_mode: ["chat", "multimodal", "workflow"],
    architecture: ["multimodal", "structured-output", "prompting"],
    maturity: "mixed",
    audience: ["developers", "analysts", "creators"],
    tags: ["gemini", "multimodal", "templates", "prompting"],
    summary: "Templates for exploring Gemini capabilities and turning prompts into reusable workflows.",
    reusable_blocks: ["multimodal input", "structured output", "prompt template"],
    license: "varies; verify per template",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 84,
    notes: "Capture model, input modality, output contract, and failure cases for each adopted template."
  },
  {
    id: "github-copilot-docs",
    title: "GitHub Copilot Documentation",
    source_url: "https://docs.github.com/en/copilot",
    platform: "GitHub Copilot",
    source_category: "official documentation",
    type: ["docs", "workflow", "playbook"],
    use_case: ["coding", "code review", "project management", "devops"],
    format: ["docs", "guide", "reference"],
    adoption_mode: "partial",
    interaction_mode: ["ide", "chat", "review"],
    architecture: ["workspace", "repo-aware", "human-in-the-loop"],
    maturity: "production",
    audience: ["developers", "engineering teams", "maintainers"],
    tags: ["coding", "review", "pull requests", "developer productivity"],
    summary: "Official guidance for integrating Copilot into development, review, and team workflows.",
    reusable_blocks: ["context grounding", "review checklist", "developer feedback loop"],
    license: "see source",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 91,
    notes: "Use alongside repository-specific security, review, and testing requirements."
  },
  {
    id: "notion-template-gallery",
    title: "Notion Template Gallery",
    source_url: "https://www.notion.so/templates",
    platform: "Notion",
    source_category: "official marketplace",
    type: ["marketplace", "template", "workflow"],
    use_case: ["knowledge management", "project management", "operations", "planning"],
    format: ["template", "workspace", "playbook"],
    adoption_mode: "hybrid",
    interaction_mode: ["workspace", "chat", "database"],
    architecture: ["workspace", "database", "knowledge system"],
    maturity: "mixed",
    audience: ["teams", "operators", "knowledge workers"],
    tags: ["templates", "docs", "databases", "operations"],
    summary: "Reusable workspace and operating-system patterns for organizing knowledge and work.",
    reusable_blocks: ["database schema", "workflow states", "knowledge capture"],
    license: "varies; verify per template",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 85,
    notes: "Evaluate information architecture and exportability before making a template foundational."
  },
  {
    id: "miroverse",
    title: "Miroverse",
    source_url: "https://miro.com/miroverse",
    platform: "Miro",
    source_category: "official workflow gallery",
    type: ["gallery", "template", "workflow"],
    use_case: ["brainstorming", "product design", "planning", "facilitation"],
    format: ["board", "template", "playbook"],
    adoption_mode: "partial",
    interaction_mode: ["visual", "collaboration", "workflow"],
    architecture: ["visual workspace", "collaboration", "facilitation"],
    maturity: "mixed",
    audience: ["product teams", "designers", "facilitators"],
    tags: ["workshop", "ideation", "roadmap", "visual collaboration"],
    summary: "Reusable visual collaboration boards and facilitation workflows.",
    reusable_blocks: ["workshop agenda", "idea clustering", "decision mapping"],
    license: "varies; verify per template",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 80,
    notes: "Test with representative participants and measure time-to-outcome, not only visual appeal."
  },
  {
    id: "agent-skills-standard",
    title: "Agent Skills Open Standard",
    source_url: "https://agentskills.io/",
    platform: "Cross-platform",
    source_category: "open standard",
    type: ["reference", "standard", "workflow"],
    use_case: ["agent interoperability", "automation", "tooling"],
    format: ["specification", "docs", "reference"],
    adoption_mode: "combined",
    interaction_mode: ["agent", "tool-use"],
    architecture: ["skills", "interoperability", "capability packaging"],
    maturity: "emerging",
    audience: ["platform engineers", "agent builders", "developers"],
    tags: ["skills", "standard", "interoperability", "portable"],
    summary: "A cross-platform reference point for packaging reusable agent capabilities.",
    reusable_blocks: ["skill contract", "capability metadata", "portable instructions"],
    license: "see source",
    last_verified: "2026-09-27",
    verification_status: "url-reachable-pending-manual-review",
    reusability_score: 90,
    notes: "Use as a portability criterion; confirm implementation support before depending on it."
  }
];
